/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

/**
 * @class
 * Initializes a new instance of the AccountProperties class.
 * @constructor
 * Account specific properties.
 * @member {string} [accountEndpoint] The endpoint used by this account to
 * obtain Batch services.
 * 
 * @member {string} [provisioningState] The provisioned state of the resource.
 * Possible values include: 'Invalid', 'Creating', 'Deleting', 'Succeeded',
 * 'Failed', 'Cancelled'
 * 
 * @member {object} [autoStorage] The properties and status of any auto
 * storage associated with the account.
 * 
 * @member {string} [autoStorage.storageAccountId] Gets or sets the resource
 * id of the storage account to be used for auto storage.
 * 
 * @member {date} [autoStorage.lastKeySync] Gets or sets the UTC time at which
 * storage keys were last synced to the Batch account.
 * 
 * @member {number} [coreQuota] The core quota for this Batch account.
 * 
 * @member {number} [poolQuota] The pool quota for this Batch account.
 * 
 * @member {number} [activeJobAndJobScheduleQuota] The active job and job
 * schedule quota for this Batch account.
 * 
 */
function AccountProperties() {
}

/**
 * Defines the metadata of AccountProperties
 *
 * @returns {object} metadata of AccountProperties
 *
 */
AccountProperties.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'AccountProperties',
    type: {
      name: 'Composite',
      className: 'AccountProperties',
      modelProperties: {
        accountEndpoint: {
          required: false,
          serializedName: 'accountEndpoint',
          type: {
            name: 'String'
          }
        },
        provisioningState: {
          required: false,
          serializedName: 'provisioningState',
          type: {
            name: 'Enum',
            allowedValues: [ 'Invalid', 'Creating', 'Deleting', 'Succeeded', 'Failed', 'Cancelled' ]
          }
        },
        autoStorage: {
          required: false,
          serializedName: 'autoStorage',
          type: {
            name: 'Composite',
            className: 'AutoStorageProperties'
          }
        },
        coreQuota: {
          required: false,
          serializedName: 'coreQuota',
          type: {
            name: 'Number'
          }
        },
        poolQuota: {
          required: false,
          serializedName: 'poolQuota',
          type: {
            name: 'Number'
          }
        },
        activeJobAndJobScheduleQuota: {
          required: false,
          serializedName: 'activeJobAndJobScheduleQuota',
          type: {
            name: 'Number'
          }
        }
      }
    }
  };
};

module.exports = AccountProperties;
