/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the AccountActions class.
 * @constructor
 * Specialized action for Batch resource provider.
 * @member {string} [action] The action name.
 * 
 * @member {string} [friendlyName] The friendly name of the action.
 * 
 * @member {string} [friendlyTarget] The target of the action.
 * 
 * @member {string} [friendlyDescription] The description of the action.
 * 
 */
function AccountActions() {
}

/**
 * Defines the metadata of AccountActions
 *
 * @returns {object} metadata of AccountActions
 *
 */
AccountActions.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'AccountActions',
    type: {
      name: 'Composite',
      className: 'AccountActions',
      modelProperties: {
        action: {
          required: false,
          serializedName: 'action',
          type: {
            name: 'String'
          }
        },
        friendlyName: {
          required: false,
          serializedName: 'friendlyName',
          type: {
            name: 'String'
          }
        },
        friendlyTarget: {
          required: false,
          serializedName: 'friendlyTarget',
          type: {
            name: 'String'
          }
        },
        friendlyDescription: {
          required: false,
          serializedName: 'friendlyDescription',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = AccountActions;
