/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var util = require('util');

/**
 * @class
 * Initializes a new instance of the AccountListPoolUsageMetricsResult class.
 * @constructor
 * Response to an AccountOperation.ListPoolUsageMetrics request.
 * @member {array} [value] Gets or sets the pool usage metrics data.
 * 
 * @member {string} ['odata.nextLink'] Gets or sets the URL to get the next
 * set of results.
 * 
 */
function AccountListPoolUsageMetricsResult() {
}

util.inherits(AccountListPoolUsageMetricsResult, Array);

/**
 * Defines the metadata of AccountListPoolUsageMetricsResult
 *
 * @returns {object} metadata of AccountListPoolUsageMetricsResult
 *
 */
AccountListPoolUsageMetricsResult.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'AccountListPoolUsageMetricsResult',
    type: {
      name: 'Composite',
      className: 'AccountListPoolUsageMetricsResult',
      modelProperties: {
        value: {
          required: false,
          serializedName: '',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'PoolUsageMetricsElementType',
                type: {
                  name: 'Composite',
                  className: 'PoolUsageMetrics'
                }
            }
          }
        },
        'odata.nextLink': {
          required: false,
          serializedName: 'odata.nextLink',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = AccountListPoolUsageMetricsResult;
