/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the NodeAgentSkuInformation class.
 * @constructor
 * Information about supported node agent SKU.
 * @member {string} [nodeAgentSKU] Gets or sets the node agent SKU.
 * 
 * @member {string} [targetOS] Gets or sets the OS that the node Agent SKU is
 * targeted against.
 * 
 * @member {string} [targetOSType] Gets or sets the type of OS that the node
 * Agent SKU is targeted against. Possible values include: 'linux',
 * 'windows', 'unmapped'
 * 
 */
function NodeAgentSkuInformation() {
}

/**
 * Defines the metadata of NodeAgentSkuInformation
 *
 * @returns {object} metadata of NodeAgentSkuInformation
 *
 */
NodeAgentSkuInformation.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'NodeAgentSkuInformation',
    type: {
      name: 'Composite',
      className: 'NodeAgentSkuInformation',
      modelProperties: {
        nodeAgentSKU: {
          required: false,
          serializedName: 'nodeAgentSKU',
          type: {
            name: 'String'
          }
        },
        targetOS: {
          required: false,
          serializedName: 'targetOS',
          type: {
            name: 'String'
          }
        },
        targetOSType: {
          required: false,
          serializedName: 'targetOSType',
          type: {
            name: 'Enum',
            allowedValues: [ 'linux', 'windows', 'unmapped' ]
          }
        }
      }
    }
  };
};

module.exports = NodeAgentSkuInformation;
