/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the PoolUsageMetrics class.
 * @constructor
 * Usage metrics for a pool across an aggregation interval.
 * @member {string} [poolId] Gets or sets the id of the pool whose metrics are
 * being aggregated.
 * 
 * @member {date} [startTime] Gets or sets the start time of the aggregation
 * interval.
 * 
 * @member {date} [endTime] Gets or sets the end time of the aggregation
 * interval.
 * 
 * @member {string} [vmSize] Gets or sets the size of virtual machines in the
 * pool.  All VMs in a pool are the same size.
 * 
 * @member {number} [totalCoreHours] Gets or sets the total core hours used in
 * the pool during this aggregation interval.
 * 
 * @member {number} [dataIngressGiB] Gets or sets the cross data center
 * network ingress to the pool during this interval, in GiB.
 * 
 * @member {number} [dataEgressGiB] Gets or sets the cross data center network
 * egress from the pool during this interval, in GiB.
 * 
 */
function PoolUsageMetrics() {
}

/**
 * Defines the metadata of PoolUsageMetrics
 *
 * @returns {object} metadata of PoolUsageMetrics
 *
 */
PoolUsageMetrics.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'PoolUsageMetrics',
    type: {
      name: 'Composite',
      className: 'PoolUsageMetrics',
      modelProperties: {
        poolId: {
          required: false,
          serializedName: 'poolId',
          type: {
            name: 'String'
          }
        },
        startTime: {
          required: false,
          serializedName: 'startTime',
          type: {
            name: 'DateTime'
          }
        },
        endTime: {
          required: false,
          serializedName: 'endTime',
          type: {
            name: 'DateTime'
          }
        },
        vmSize: {
          required: false,
          serializedName: 'vmSize',
          type: {
            name: 'String'
          }
        },
        totalCoreHours: {
          required: false,
          serializedName: 'totalCoreHours',
          type: {
            name: 'Number'
          }
        },
        dataIngressGiB: {
          required: false,
          serializedName: 'dataIngressGiB',
          type: {
            name: 'Number'
          }
        },
        dataEgressGiB: {
          required: false,
          serializedName: 'dataEgressGiB',
          type: {
            name: 'Number'
          }
        }
      }
    }
  };
};

module.exports = PoolUsageMetrics;
